"""add weight and height to crew_members

Revision ID: 8f2fddb7a909
Revises: 78ac8bcd2856
Create Date: 2025-05-02 15:02:32.251390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2fddb7a909'
down_revision: Union[str, None] = '78ac8bcd2856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_members', sa.Column('height', sa.Float(), nullable=False))
    op.add_column('crew_members', sa.Column('weight', sa.Float(), nullable=False))
    op.drop_column('crew_members', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_members', sa.Column('role', sa.VARCHAR(), nullable=False))
    op.drop_column('crew_members', 'weight')
    op.drop_column('crew_members', 'height')
    # ### end Alembic commands ###
