"""create shipping_data table

Revision ID: e6ad033c7d79
Revises: aa92385f3394
Create Date: 2025-05-12 01:13:31.151660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ad033c7d79'
down_revision: Union[str, None] = 'aa92385f3394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Create the shipping_data table ###
    op.create_table(
        'shipping_data',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('voyage_number', sa.String, nullable=False),
        sa.Column('departure_date', sa.DateTime, nullable=False),
        sa.Column('arrival_date', sa.DateTime, nullable=False),
        sa.Column('season', sa.Enum('Spring', 'Summer', 'Autumn', 'Winter', name='seasons'), nullable=False),
        sa.Column('description', sa.String, nullable=True),
        sa.Column('is_current', sa.Boolean, nullable=False, server_default="false", index=True),
        sa.Column('created_at', sa.DateTime, default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime, default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
